// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTmabWDtrxu2G6deq4CHjguQfcd1lS1OI',
    appId: '1:747290558958:web:4ffa7939c47ec8b19cceff',
    messagingSenderId: '747290558958',
    projectId: 'meeting-scheduler-7902f',
    authDomain: 'meeting-scheduler-7902f.firebaseapp.com',
    storageBucket: 'meeting-scheduler-7902f.firebasestorage.app',
    measurementId: 'G-ZP8FTWJV26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCapVhyXbrcf07B4QR0FBo7h4N5wPGRNQg',
    appId: '1:747290558958:android:739d1753b1b44fa49cceff',
    messagingSenderId: '747290558958',
    projectId: 'meeting-scheduler-7902f',
    storageBucket: 'meeting-scheduler-7902f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxxQHrTds2kBSNUCZ_JS88cMO2Rnn9Gq0',
    appId: '1:747290558958:ios:35a5ddea543a56ac9cceff',
    messagingSenderId: '747290558958',
    projectId: 'meeting-scheduler-7902f',
    storageBucket: 'meeting-scheduler-7902f.firebasestorage.app',
    iosBundleId: 'com.example.meetingScheduler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxxQHrTds2kBSNUCZ_JS88cMO2Rnn9Gq0',
    appId: '1:747290558958:ios:35a5ddea543a56ac9cceff',
    messagingSenderId: '747290558958',
    projectId: 'meeting-scheduler-7902f',
    storageBucket: 'meeting-scheduler-7902f.firebasestorage.app',
    iosBundleId: 'com.example.meetingScheduler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTmabWDtrxu2G6deq4CHjguQfcd1lS1OI',
    appId: '1:747290558958:web:36fe7101547900939cceff',
    messagingSenderId: '747290558958',
    projectId: 'meeting-scheduler-7902f',
    authDomain: 'meeting-scheduler-7902f.firebaseapp.com',
    storageBucket: 'meeting-scheduler-7902f.firebasestorage.app',
    measurementId: 'G-DC7LP5C9DZ',
  );
}
